-- UserRole
CREATE TABLE UserRole (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  CONSTRAINT fk_userrole_user FOREIGN KEY (user_id) REFERENCES `User`(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_userrole_role FOREIGN KEY (role_id) REFERENCES Role(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY ux_userrole_user_role (user_id, role_id)
);